#--------------------------------------- SOLAS additions

#--------------------------------------- Metal parameters
metals: ON                  # Advect all metals, ie metal mass fraction, as a PASSIVE_SCALARS

#--------------------------------------- Cooling parameters
use_grackle: ON  # use grackle
grackle_chemistry: 3

#--------------------------------------- Star Formation options
agora_sf: ON                # Agora based SF

#--------------------------------------- Star options
stars: ON                   # General stars framework flag

star_particles: 1       # star particles model flag: set to 0, 1 for massive star particles, set to 2 for resolved individual stars

star_feedback: OFF           # Include full star feedback (winds + full radiation + supernovae)
winds: ON                   # Only winds
radiation: OFF               # Full radiation
supernovae: ON              # Only supernovae

star_host_refinement: OFF   # no gas containing star refinement


#--------------------------------------- Arepo public

#--------------------------------------- Mesh motion and regularization; default: moving mesh
regularize_mesh_cm_drift: ON       # Mesh regularization; Move mesh generating point towards center of mass to make cells rounder.
regularize_mesh_cm_drift_use_soundspeed: ON   # Limit mesh regularization speed by local sound speed
regularize_mesh_face_angle: ON     # Use maximum face angle as roundness criterion in mesh regularization

#--------------------------------------- Refinement and derefinement; default: no refinement/derefinement; criterion: target mass
refinement_split_cells: ON         # Refinement
refinement_merge_cells: ON         # Derefinement
refinement_volume_limit: ON        # Limit the volume of cells and the maximum volume difference between neighboring cels
noderefine_background_grid: ON     # Do not de-refine low-res gas cells in zoom simulations

#--------------------------------------- non-standard phyiscs
cooling: ON                        # Simple primordial cooling
use_sfr: ON                        # Star formation model, turning dense gas into collisionless partices

#--------------------------------------- Gravity treatment; default: no gravity
selfgravity: ON                    # gravitational intraction between simulation particles/cells
hierarchical_gravity: ON           # use hierarchical splitting of the time integration of the gravity
cell_center_gravity: ON            # uses geometric centers to calculate gravity of cells, only possible with HIERARCHICAL_GRAVITY
gravity_not_periodic: ON           # gravity is not treated periodically
allow_direct_summation: ON         # Performed direct summation instead of tree-based gravity if number of active particles < DIRECT_SUMMATION_THRESHOLD (= 3000 unless specified differently here)
direct_summation_threshold: 500  # overrides maximum number of active particles for which direct summation is performed instead of tree based calculation

#--------------------------------------- Gravity softening
nsofttypes: 4                  # number of different softening values to which particle types can be mapped.
multiple_node_softening: ON        # If a tree node is to be used which is softened, this is done with the softenings of its different mass components
adaptive_hydro_softening: ON       # Adaptive softening of gas cells depending on their size

#--------------------------------------- Time integration options
tree_based_timesteps: ON           # non-local timestep criterion (take 'signal speed' into account)

#--------------------------------------- Single/Double Precision
doubleprecision: 1             # mode of double precision: not defined: single; 1: full double precision 2: mixed, 3: mixed, fewer single precisions; unless short of memory, use 1.
ngb_tree_doubleprecision: OFF       # if this is enabled, double precision is used for the neighbor node extension

#--------------------------------------- output options
process_times_of_outputlist: ON    # goes through times of output list prior to starting the simulaiton to ensure that outputs are written as close to the desired time as possible (as opposed to at next possible time if this flag is not active)
have_hdf5: ON                      # needed when HDF5 I/O support is desired (recommended)

#--------------------------------------- Testing and Debugging options
debug: ON                          # enables core-dumps

override_peanogrid_warning: ON   # don't stop if peanogrid is not fine enough
